### ISSUE TITLE
This is awesome! 

### ISSUE THREAD

**Issue by mmahalwy** [karimfikry/wavesurfer-angular#3]
Love it! 

But need it to be more flexible in terms of the design and elements. Going to fork this

**Comment by karimfikry** [comment]
Thanks man!

I'm not professional with design issues and I implemented it fast. Fork it and if you have any update just send me a pull request!

**Comment by mmahalwy** [comment]
Sounds good! Going to add this to the new audio.quran.com :) (currently Quranicaudio.com)

**Comment by karimfikry** [comment]
Sounds great!
