### ISSUE TITLE
Limit total audio files playing to 1 with option

### ISSUE THREAD

**Issue by jjn2009** [karimfikry/wavesurfer-angular#5]
Might be useful to let others specify they only want to have one audio file playing at a time. e.g. I play a sound all active sounds get paused automatically. (having specified an option that I want that to be the behavior to this angular directive).

I did a quick look at wavesurferjs and it doesn't seem to do this.

**Comment by karimfikry** [comment]
It's because of using unique ID. Just I was planning to play one audio file, so If you want multiple audio files, It can be done in another way instead of adding an id. Maybe adding a random number besides the id or get it using selector like

element.children()[index]

**Comment by jjn2009** [comment]
Ah yeah I guess this issue isn't relevant unless you were wanting to accept my pull request. If not that's fine, I'll keep developing my own fork if you don't want to go that direction.

**Comment by karimfikry** [comment]
Yeah! I'm testing it and I'll accept it.

**Comment by jjn2009** [comment]
Great. I look forward to making more pull requests.
